### ISSUE TITLE
page reload in the background. reverse proxy.

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.web#45]
there are two instances of the web adapter. One for local access without a password (web.0), and the other with authorization (web.1). When working through a direct ip address (web.0), you can open 2-3 tabs with iobroker (log, scripts, objects) without issue. when opening one tab via reverse proxy, it starts to reload if not in focus, usually after 5-10 minutes. 
I noticed that the problem appeared relatively recently, it seems when updating on js-controller to version 3

---

**System data:**

Platform: linux
Distribution: Debian GNU/Linux
Architecture: x64
Model: Intel(R) Celeron(R) CPU G1610T @ 2.30GHz
RAM: 9.73 GB
Node.js: v12.16.2
NPM: 6.14.4
Model: ARMv7 Processor rev 4 (v7l)
RAM: 975.61 MB
Node.js: v12.16.2
NPM: 6.14.4
JS-Controller (1): 3.0.20
Admin: 4.1.1
WEB server: 3.0.8

> *created by ioBroker.info*

**Comment by Apollon77** [comment]
All what you describe is admin and not web or what exactly do you mean/do? 

Normally in admin the reload happens when the socket.io connection is no longer doing "PING/PONG" (normally every 20-30s). Browser tabs in the background partially stop being eecuted so it could also happen with other tabs.
I could think of that no socket.io/websocket connection is done via reverse proxy and so long polling is used and so the "inactivity" has different effects, but in fact you need to check that.

**Comment by Apollon77** [comment]
If this is the reason then I do not see anything we can do.

Please try if it also happens if you do not open tabs but parallel browser windowsin same browser (because then they all stay "active" at the same time and it sgould not happen. If this is the case then browsers stiopping the execution of javascript in inactive tabs is the reason

**Comment by Anzic23** [comment]
if I leave the browser window "hanging" next to it, and I use another window, then the restart does not occur, but if I hide the tab for another, then the hidden tab is reloaded (just noticed on objects and scripts)

**Comment by Apollon77** [comment]
Then the assumption is as said. The browser stops the JavaScript in the not active tab which leads to the fact that the socketio 20s pingpong is not done and this is handled like a reconnect. you can try to compare the network viel from browsers when using reverse proxy or not and maybe you see different socketio behavior ?!

**Comment by Anzic23** [comment]
if I don't use a reverse proxy, there is no reset in the background, which is what I'm talking about in the first message. The tab is reloaded only when using the reverse proxy. On the controller 2.x worked normally both through the reverse proxy and directly.

**Comment by Apollon77** [comment]
This is the interesting part .... the Controller should have no effect at all on how web adapter handles its connections. Or was it also updating web to 3.x from 2.x before?

**Comment by Anzic23** [comment]
I have a different setup. web 3.0.0 admin 4.0.2 js-controller 2.2.8. it works via reverse proxy without any reloads, at least 5 tabs.

**Comment by Anzic23** [comment]
![image](https://user-images.githubusercontent.com/37106885/82582419-b4def180-9b9a-11ea-8d1a-f5f11fbf66e5.png)
maybe this will help?

**Comment by Apollon77** [comment]
And on which combination it works? Whith just downgrading Controller?

**Comment by Anzic23** [comment]
web 3.0.0 admin 4.0.2 js-controller 2.2.8 work well
web 3.0.8 admin 4.1.1 js-controller 3.1.4 reloads in background
